### ISSUE TITLE
Add osx to travis builds

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpscore#429]
**Is your feature request related to a problem? Please describe.**
`travis`'matrix does not yet include `osx` 

**Describe the solution you'd like**
```    
- name: osx
   os: osx
   osx_image: xcode11
   compiler: clang
    script:
       - mkdir build && cd build
       - cmake  ..
       - make -j $(nproc)
```
**Describe alternatives you've considered**
Alternativlos! ^^

**Additional context**

<img width="763" alt="Screenshot 2019-07-19 17 09 10" src="https://user-images.githubusercontent.com/5772973/61548551-8840e180-aa80-11e9-854e-86305ea96d99.png">

**Comment by schroedtert** [comment]
I’m currently working on it. But I ran into the following problem:
When using Mac + g++ it get the following error:
```
[100%] Linking CXX executable bin/boost-unit-tests
404 Undefined symbols for architecture x86_64:
405  "boost::unit_test::ut_detail::normalize_test_case_name[abi:cxx11](boost::unit_test::basic_cstring<char const>)", referenced from:
406      boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long) in testClassLineBoost.cpp.o
407      boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long) in testClassObstacleBoost.cpp.o
408      boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long) in testClassPointBoost.cpp.o
409      __GLOBAL__sub_I_testClassRoomBoost.cpp in testClassRoomBoost.cpp.o
410      __GLOBAL__sub_I_testClassWallBoost.cpp in testClassWallBoost.cpp.o
411      boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long) in testSubRoomBoost.cpp.o
412 ld: symbol(s) not found for architecture x86_64
413 collect2: error: ld returned 1 exit status
414 make[2]: *** [bin/boost-unit-tests] Error 1
415 make[1]: *** [CMakeFiles/boost-unit-tests.dir/all] Error 2
416 make: *** [all] Error 2
417 The command "make -j $(nproc)" exited with 2.
```
Full info at https://travis-ci.com/schroedtert/jpscore/jobs/225431971

With the following .travis.yml (just an extract):
```
    - os: osx
      osx_image: xcode10.2
      env: TOOLCHAIN=gcc
      script:
        - mkdir build && cd build
        - cmake  .. -DBUILD_CPPUNIT_TEST=ON -DBUILD_TESTING=ON -DAIROUTER=ON -DJPSFIRE=ON -DCMAKE_CXX_COMPILER=g++-8
        - make -j $(nproc)
```

Remark: Seems that we can not use more modern Xcode, as a dependency in poly2tri forces Xcode < 10.5.
